# Generated by Django 4.1 on 2024-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="blog/images/&Y/%m/%d/"),
        ),
    ]
