# Generated by Django 4.1 on 2024-11-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_post_head_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tag",
            new_name="tags",
        ),
    ]
